[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "beatbangermania"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = ["Pillow"]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
beatbangermania = "beatbangermania.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
